lib/cli.js

fixes: typo in cli argument

---

lib/app/js/app.js
lib/app/js/controllers/main.js
lib/app/js/controllers/sections.js

Search have performance issues with big styleguide since it returns every result with an empty string. After this change the search returns empty set with an empty string

New route for search. Do not allow searches less than 3 chars

---

README.md

Improving `README.md` readability by using syntax highlight for code blocks.

Using GH syntax highlight in README for improved readibility

---

README.md
lib/modules/variable-parser.js
test/unit/modules/variable-parser.test.js

Add possibility to ignore lines from being processed using tags:
```
// styleguide:ignore:start
Ignored styles
// styleguide:ignore:end
```

Add possibility to ignore parts of the style files from processing

---

README.md
lib/styleguide.js

This allows to including external files in custom variable file

Add directory of custom colors file to SASS includePaths

---

lib/modules/cli/styleguide-cli.js

customColors, disableEncapsulation and filesConfig options were not passed before, when using cli

Support all options via cli

---

lib/modules/cli/styleguide-cli.js

Reverts SC5/sc5-styleguide#675

Revert "Support all options via cli"

---

lib/app/js/app.js
test/angular/unit/app.test.js

PR with @paul-barry-kenzan changes. Taken from https://github.com/SC5/sc5-styleguide/pull/693

Allowed for variable chaining

---

lib/app/sass/app.scss
lib/app/views/element-fullscreen.html
lib/app/views/main.html
lib/app/views/partials/design.html
lib/app/views/partials/section.html
lib/app/views/partials/variable.html
lib/app/views/variable-sections.html

Cleaned https://github.com/SC5/sc5-styleguide/pull/642 by @wini16

Prefixed css classes with sg- so they don't conflict with user's css

---

gulpfile.js

Reverts SC5/sc5-styleguide#743

Revert "Missing files in dist. Fix #734" (mistaken merge into master)

---

README.md

Reverts SC5/sc5-styleguide#752

Revert "Improve setup instructions, spelling, consistency"

---

README.md

Improve setup instructions, spelling, consistency (PR to dev branch)

---

lib/app/js/controllers/element.js

Possibility to include all section elements in fullscreen mode using `?recursive` query parameter.

Possibility to include all section elements in fullscreen mode

---

lib/app/sass/_styleguide_variables.scss
lib/app/sass/styleguide-app.scss

* Make header paddings consistent
* Possibility to define submenu height
* Possibility to define different source text color for main section
* Possibility to define header height

Improve UI and customization variables

---

package.json

@glebmachine I changed the package dependency. We need everything to be installed from npm, at least for versioning. Do you mind?

Install the packages from npm

---

lib/app/sass/styleguide_helper_elements.scss

Tables processing has been enabled but the styles are missing. Please refer to https://github.com/SC5/sc5-styleguide/issues/783

Adding styles for table.

---

lib/app/index.html

Reverts SC5/sc5-styleguide#888

Revert "Helper CSS is included into the app CSS, no need to load. Fix #887"

---

lib/styleguide.js

Issue [#961](https://github.com/SC5/sc5-styleguide/issues/961)

#961 Tweak bemto.jade path dynamically

---

package.json

Update `gonzales-pe` to 3.4.4 and make the dependency less strict

Update gonzales-pe to a newer version

---

test/unit/modules/parsers/less.test.js
test/unit/modules/parsers/postcss.test.js

Unit test for not considering spaces in variable definitions

---

package.json

Bump to socket.io 1.4.0

---

README.md
lib/app/css/_fontpath_and_mixin_definition.css
lib/app/css/_styleguide_default_styles.css
lib/app/views/main.html
lib/app/views/partials/design.html
lib/app/views/partials/section.html
lib/app/views/sections.html
lib/modules/common.js
lib/styleguide.js

Added build option showReferenceNumbers, false by default

Added build option showReferenceNumbers

---

lib/styleguide.js

@DanielaValero Thanks for reporting the problem I fixed it

Fix #1088 customstyles missing on clean install

---

gulpfile.babel.js
lib/modules/cli/argv.js
lib/modules/cli/styleguide-cli.js
lib/modules/common.js
lib/styleguide.js
test/integration/assert-index-html.js
test/integration/npm-package.test.js
test/integration/test-config.js

Fixed the default styles on clean build

Fix styles clean build

---

lib/app/views/partials/section.html
lib/app/views/sections.html

- fixed mismatched classes on the code partials
- made all containers `code[hljs]`
@varya

made "sections" more consistent

---

lib/modules/cli/argv.js
lib/modules/cli/styleguide-cli.js

favIcon option did not work because it was not set to options object.
I fixed the code, so please merge my update.
Thank you!

Adding favIcon config
