SC5/sc5-styleguide

- lib/modules/cli/argv.js
- lib/modules/cli/styleguide-cli.js
- test/integration/assert-at-rules.js
- test/integration/assert-index-html.js
- test/integration/assert-overview-html.js
- test/integration/assert-pseudo-styles.js
- test/integration/assert-styleguide-css.js
- test/integration/assert-styleguide-json.js
- test/integration/assert-template.js
- test/integration/assertions.js
- test/integration/npm-package.test.js
- test/integration/structure.test.js
- test/integration/test-config.js
- test/unit/modules/cli/argv.test.js
Use the same assertions on the style guides generated via the executable as used in test/integration/structure.test.js
> Improve npm package integration tests, fix missing CLI arguments

- lib/app/index.html
- lib/app/sass/app.scss
We want to application styles to be applied after user styles to prevent user style leaking to application. also reset commonly used font-style parameter that is inheritable.
> Change CSS order to prevent leakages when not using encapsulation

- test/integration/structure.test.js
The documentation at https://github.com/rvagg/through2 states "Note that through2.obj(fn) is a convenience wrapper around through2({ objectMode: true }, fn)."
> Fix through2 obj call syntax

- lib/styleguide.js
It is possible that the CSS is not valid anymore after it is spliced to sections.
We need to catch possible parsing errors
> Catch errors when finding used variables

- lib/app/sass/app.scss
When shadow DOM is disables this property could easily leak from user defined styles
> Define border also on input focus styles

- README.md
- add `var gulp = require('gulp');
> Update README gulp example

- lib/app/index.html
- lib/app/views/partials/design.html
Since we need to trust JSON contents anyway, it is not a problem to use unsafe filter.
> Support special characters on page title and on designer tool, fixes #664

- lib/modules/parsers/less.js
- lib/modules/parsers/scss.js
- test/unit/modules/parsers/less.test.js
- test/unit/modules/parsers/scss.test.js
Fixes issue when wrong variable was saved when save variable name was used inside a function in the variable value: `$another: lighten($mycolor, 10%);`
> Refactor variable setter. Fixes variable saving issues. Add test cases

- lib/app/sass/app.scss
- lib/app/views/element-fullscreen.html
Navigation links have default colors, which makes them purple when they are visited. This is crucial for automatic visual testing (comparing screenshots of development and production version of the interface).
The change gives the navigation links permanent color.
Also, it is nice in general that a visible element has class and can be styled.
> Make navigation links for a fullscreen view the same when visited and not

- lib/modules/kss-parser.js
Solves silent styleguide's generation fail on KSS errors. Issue: https://github.com/SC5/sc5-styleguide/issues/765
> Show KSS parse errors

- lib/app/js/controllers/element.js
- lib/app/js/controllers/sections.js
- lib/app/views/partials/section.html
- lib/modules/wrapper-markup.js
- test/angular/unit/controllers/element.test.js
- test/angular/unit/controllers/sections.test.js
- test/unit/modules/wrapper-markup.test.js
I made this renaming because the markup to render may have many transformations, not only to be wrapped. This will also matter in our future introduction of `sg-htmlMarkup` property.
> Renamed wrappedMarkup property into renderMarkupPropery

- lib/app/index.html
- test/integration/assert-index-html.js
Replaces the second occurrence of /css
See https://github.com/SC5/sc5-styleguide/commit/b8de9149b88dd08fb2600e71d078c45d2dfb2da4
Fixes #716
> Correct path to helper elements CSS. Fixes #799

- README.md
- lib/modules/section-references.js
- test/unit/modules/section-references.test.js
see https://github.com/SC5/sc5-styleguide/issues/784
> first shot at including modifiers

- gulpfile.babel.js
Currently in dev mode styles are not applied to the components in shadowRoot. The generated `styleguide.css` is empty because there is no `distPath + '/css/*.css'` file (check on pure copy, or after removing `lib/dist`). The problem appeared on 0.3.20 version.
The proposed change solves the problem but it makes copy-paste with similar code of `lib/styleguide.js`.
Before:
After:
> Process sass files before giving them to styleguide for applying

- gulpfile.babel.js
- package.json
The problem https://github.com/SC5/sc5-styleguide/pull/840 fixes would have been noticed a lot sooner if previous build results were cleared before the next build.
> Run clean task before build to remove previous build results

- README.md
- lib/modules/section-references.js
- test/unit/modules/section-references.test.js
This pr should fix https://github.com/SC5/sc5-styleguide/issues/748
Previously the sectionRefrence.replaceReferences function only replaced sg-includes in the markup variable of the given sections. Now includes are replaced in the 'sg-wrapper' variable as well. 
This test input: 
```
// List item
//
// markup:
// <li>Item</li>
//
// Styleguide 4.0.1
li {
color: red;
}
// List footer
//
// markup:
// <div>
//   <p>hej</p>
// </div>
//
// sg-wrapper:
// <ul>
//   <li>hop</li>
//   <sg-insert>4.0.1</sg-insert>
// </ul>
// <sg-wrapper-content/>
//
// Styleguide 4.0.2
```
Without the fix the styles are rendered like this:
When the contents in the sg-wrapper is replaced the same styles are rendered like this:
> Replace inserts in wrappers

- README.md
- lib/app/index.html
- lib/modules/cli/argv.js
- lib/modules/cli/styleguide-cli.js
- lib/modules/common.js
- lib/styleguide.js
This will make possible to use SVG inserts, as is asked in #819. Also can be used for anything else.
> Options to inject custom HTML in beginning or in the end of <body> tag

- lib/styleguide.js
- package.json
- Since now, jade compiled markup are cached between launches (got a headache on huge project).
- JS Errors now prints callstack, instead of naked error message itself
I have added LocalCache lib, with same api like LocalStorage. It store all cached data to `.json` file (rootPath + 'jadecache.json'). File creating only with `jadeEnabled` : `true` flag.
> Jade cache, level 2 

- package.json
The `gulp-jshint` 2.0 package requires `jshint` to be installed manually.
> Add missing jshint dependency

- package.json
- test/unit/modules/cli/index.test.js
- test/unit/modules/cli/styleguide-cli.test.js
With Babel 6 removing the babel package, switched to babel-core.
Added some tests to get pull approved.
> Fix #904. Updating the babel package.

- lib/styleguide.js
This is basically a quick fix to make sure you can have includes from your project in the jade markup of a component.
This sets the root for all absolute paths to the main folder of your app so that you can use absolutes to set up includes in your jade markup.
> Add possibility to have includes in jade markup

- lib/styleguide.js
... instead of dumping the whole exception object
> Show only the exception message on compile error

- README.md
- gulpfile.babel.js
- lib/app/css/styleguide-app.css
- lib/app/index.html
- lib/app/js/controllers/main.js
- lib/app/js/controllers/sections.js
- lib/app/views/main.html
- lib/modules/cli/argv.js
- lib/modules/cli/styleguide-cli.js
- lib/modules/common.js
- lib/styleguide.js
- test/angular/unit/controllers/main.test.js
- test/angular/unit/controllers/sections.test.js
Side navigation
Third navigation level
Prevent to load sections on main navigation level
Hamburger menu styles on mobile view (only with sidebar nav)
> Feature navigation

- lib/app/js/app.js
Updated pull request: 
We have quite large styleguide and seems that setVariables filter have some performance problems. 
Our variables arrays has almost 300 items and using _.memoize in some pages we can reduce cpu 100% usage from ~65s -> ~2.5s.
> optimize filter setVariables

- lib/app/css/styleguide-app.css
This adds the missing calc() so the search field gets its margin-top back.
Cheers
Veit
> fix css for search field

- lib/styleguide.js
The `styleguide.server()` method should return the instance of the `sgServer` to do further optimizations to it.
> Return server instance when calling styleguide.server()

- bower.json
- lib/app/css/styleguide-app.css
It was not a angular issue - all things are there to enable smooth scrolling using anchor links. It was a css thing that causes js based scrolling not to work.
> Fixes #42. Scrolling from javascript not working when overflow: auto is set on body.

- bower.json
I noticed that my recent PR to upgrade the project dependencies allowed angular-mocks to get out of sync with angular and angular-animate. This caused an issue when I did a fresh install today and the angular versions got out of sync. This PR makes sure that the angular-mocks version exactly matches angular.
> Fix angular-mocks version

- lib/app/views/partials/section.html
A multi-block description already creates as many paragraphs as there are "blocks" of description and the partial view `section.html` nests it in a parent paragraph, which is invalid HTML and may cause several problem (with browser parsers, with screen-readers and other assistive technologies).
Changing container `.sg-section-description` for a `div` avoids nested `p`.
Example with this 3 paragraphs-long description:
```
// Title of section
//
// Paragraph 1
//
// Paragraph 2
//
// Paragraph 3
//
// markup: (…)
```
would now result in:
```
<div ng-bind-html="section.description |&nbsp;unsafe" class="sg sg-section-description ng-binding">
<p class="sg">Paragraph 1</p>
<p class="sg">Paragraph 2</p>
<p class="sg">Paragraph 3</p>
</div>
```
With this modification, single-line descriptions are …
> Avoid nested paragraphs in description

- lib/app/index.html
See issue 988 for details
https://github.com/SC5/sc5-styleguide/issues/988
> Removed appRoot property from socket.io script src to stop 404

- lib/app/css/styleguide-app.css
Fixed an issue where overriding the $content-max-width SCSS variable using the 'customColors' config property was not having an effect on the .sg-wrapper CSS class because of a hard-coded value.
> Fixed a styleguide styling issue regarding the $content-max-width scss variable

- lib/app/js/app.js
When you add your own directives in the filesConfig property, they are loaded via ocLazyLoad in the resolve property for every $state in the Styleguide App. 
error: as the ocLazyLoading promise is not being returned in the resolve, you might experience some weird errors saying that  your directives are not defined, also, when you reload the browser, sometimes you will experience an error with $$animateJS 
the $$animateJS error is related to https://github.com/angular/angular.js/issues/14291
also, I added the return statement in the resolve property to return the ocLazyLoad promise so the view will not be printed until all the modules are loaded.
> Fix to return the ocLazyLoading promise on resolve

- lib/app/css/styleguide-app.css
- lib/app/views/main.html
I use the sidenav option a lot for large styleguides. The layout had a set overflow with scrollbars always showing and was cumbersome to navigate. This commit ensures adequate vertical space for the sidenav, removes persistent scrollbars, and toggles correctly in mobile views. Tested in Chrome, Firefox, Safari, Edge, and IE 11.
> Fix layout and mobile toggle for sidenav  option

- README.md
Without the return styleguide.applystyles() never creates the following files:
* styleguide.css
* styleguide_pseudo_styles.css
* styleguide_at_rules.css
> Update README.md Grunt Example

- lib/styleguide.js
This PR addresses #1054 by printing out a helpful error message to the console using gonzales-pe `error.toString()` method.
> Output meaningful error message to the console; fixes #1054

- lib/app/views/main.html
- lib/app/views/sections.html
Related to this PR: https://github.com/SC5/sc5-styleguide/commit/edfccd193f510011e7ac1aac017e1317092988fc
It was returning the following error when visiting `subsections` from the main menu.
> Replace smart quotes with straight quotes

- lib/modules/kss-parser.js
since sc5 comes baked in with pug/jade, it would only make sense to allow for .pug files to be passed in like html or hbs files.
@varya
> allow .pug files to be passed into markup

- package.json
- Fix missing `mocha` package devDependency that was causing test suite to fail to work.
Reason for the change:
- Test suite fails without of the required dependencies.
Related issue:
- https://github.com/SC5/sc5-styleguide/issues/1117
- _"Test suite fails to run without mocha dependency"_
> fix(package.json) fix failing test suite

- lib/styleguide.js
Ready for code review.
Fixes #1128 and #1115.
> Use parsed includeDefaultStyles instead of direct input
